# Generated by Django 5.2.14 on 2026-06-09 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('created', 'Created')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.PositiveIntegerField(blank=True, null=True)),
                ('child_gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('neutral', 'Neutral')], max_length=20)),
                ('child_hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('child_skin_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('child_secondary_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.booktemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='child_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='books.bookrequest')),
                ('book_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='books.bookresult')),
            ],
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated_books/pages/')),
                ('is_preview', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pagetemplate')),
                ('book_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='books.bookresult')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('book_result', 'page_number')},
            },
        ),
    ]
