# Generated by Django 6.0.6 on 2026-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookrequest_book_template_alter_bookrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewrequest',
            name='child_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previewrequest',
            name='child_gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='previewrequest',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
