# Generated by Django 6.0.6 on 2026-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_previewrequest_child_age_previewrequest_child_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
