# Generated by Django 6.0.6 on 2026-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_previewrequest_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='generated_svg',
            field=models.FileField(blank=True, null=True, upload_to='generated_books/svgs/'),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='raw_image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_books/pages/'),
        ),
        migrations.AddField(
            model_name='previewresult',
            name='generated_svg',
            field=models.FileField(blank=True, null=True, upload_to='previews/svgs/'),
        ),
        migrations.AddField(
            model_name='previewresult',
            name='raw_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/pages/'),
        ),
    ]
