# Generated by Django 6.0.6 on 2026-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfyui_url', models.CharField(default='http://localhost:8188', help_text='ComfyUI server URL', max_length=255)),
                ('under_maintenance', models.BooleanField(default=False, help_text='Enable maintenance mode for frontend')),
                ('entity_name', models.CharField(default='MD AAQIF', max_length=255)),
                ('registered_address', models.TextField(default='B-278/ GALI NO-4, JAITPUR PART-2, KHADDA COLONY, NEAR SONI MODERN PUBLIC SCHOOL, NEW DELHI-110044')),
                ('support_phone', models.CharField(default='+91 8506021247', max_length=50)),
                ('support_email', models.CharField(default='support@wondertale.in', max_length=255)),
                ('support_hours', models.CharField(default='Mon - Fri, 10:00 AM - 6:00 PM', max_length=255)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('is_tax_included', models.BooleanField(default=True)),
                ('tax_note', models.CharField(default='Inclusive of all taxes', max_length=100)),
                ('estimated_delivery_time', models.CharField(default='7-8 working days', max_length=100)),
                ('shipping_regions', models.TextField(default='Deliveries available across all pin codes in India.')),
                ('courier_partners', models.TextField(default='Delhivery, BlueDart, and Speed Post')),
                ('dispatch_timeline', models.CharField(default='Dispatched within 24-48 hours after photo approval.', max_length=255)),
                ('cancellation_window_hours', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
