# Generated by Django 6.0.6 on 2026-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hardcover_image',
            field=models.ImageField(blank=True, null=True, upload_to='config/pricing/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='softcover_image',
            field=models.ImageField(blank=True, null=True, upload_to='config/pricing/'),
        ),
    ]
