# Generated by Django 6.0.6 on 2026-07-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_siteconfiguration_hardcover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='crafting_max',
            field=models.IntegerField(default=50, help_text='Maximum range for stories being crafted counter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='crafting_min',
            field=models.IntegerField(default=8, help_text='Minimum range for stories being crafted counter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='viewing_max',
            field=models.IntegerField(default=99, help_text='Maximum range for active page viewers counter'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='viewing_min',
            field=models.IntegerField(default=60, help_text='Minimum range for active page viewers counter'),
        ),
    ]
