# Generated by Django 6.0.6 on 2026-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_siteconfiguration_crafting_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='announcement_enabled',
            field=models.BooleanField(default=True, help_text='Enable top header announcement bar'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='announcement_text',
            field=models.CharField(blank=True, default='✨ New Story Alert: "The Crystal Cave" is now available for personalization! ✨', help_text='Top header announcement text', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_bar_enabled',
            field=models.BooleanField(default=True, help_text='Enable promotional discount banner'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='discount_bar_text',
            field=models.CharField(blank=True, default='⚡ Limited Time Offer: Save up to 33% OFF on all custom storybooks today!', help_text='Promotional discount banner text', max_length=255),
        ),
    ]
