# Generated by Django 6.0.6 on 2026-06-12 10:01

import os
from django.db import migrations, models

def migrate_existing_images(apps, schema_editor):
    PageTemplate = apps.get_model('catalog', 'PageTemplate')
    for page in PageTemplate.objects.all():
        if page.image:
            filename = os.path.basename(page.image.name)
            page.image_name = filename
            
            name, ext = os.path.splitext(filename)
            page.mask_image_name = f"{name}_mask{ext}"
            page.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagetemplate',
            name='mask_image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            migrate_existing_images,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='pagetemplate',
            name='image',
        ),
    ]
