# Generated by Django 6.0.6 on 2026-06-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_age_range_product_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover_image',
        ),
    ]
