# Generated by Django 6.0.6 on 2026-06-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpreviewimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productpreviewimage',
            name='image',
            field=models.ImageField(default='', upload_to='catalog/previews/'),
            preserve_default=False,
        ),
    ]
