# Generated by Django 6.0.6 on 2026-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_productpreviewimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetemplate',
            name='svg_template',
            field=models.FileField(default='templates/svgs/default.svg', upload_to='templates/svgs/'),
        ),
    ]
