# Generated by Django 6.0.6 on 2026-07-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_pagetemplate_svg_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetemplate',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='pagetemplate',
            name='mask_image_name',
        ),
        migrations.AddField(
            model_name='pagetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/pages/images/'),
        ),
        migrations.AddField(
            model_name='pagetemplate',
            name='mask_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/pages/masks/'),
        ),
    ]
