# Generated by Django 6.0.6 on 2026-07-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_pagetemplate_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeafterslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AddField(
            model_name='beforeafterslide',
            name='slide_type',
            field=models.CharField(choices=[('before_after', 'Before-After'), ('static', 'Static')], default='before_after', max_length=20),
        ),
        migrations.AlterField(
            model_name='beforeafterslide',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='beforeafterslide',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
    ]
