# Generated by Django 6.0.6 on 2026-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_beforeafterslide_image_beforeafterslide_slide_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price_hardcover',
            field=models.PositiveIntegerField(default=1999, help_text='Original list price / MRP before discount for hardcover'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price_softcover',
            field=models.PositiveIntegerField(default=1499, help_text='Original list price / MRP before discount for softcover'),
        ),
    ]
