# Generated by Django 6.0.6 on 2026-07-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('storybook', 'Personalized Storybook'), ('frame', 'Personalized Photo Frame'), ('sticker', 'Personalized Sticker'), ('label', 'Personalized Name Label')], default='storybook', max_length=50),
        ),
    ]
